# Generated by Django 5.2.4 on 2025-09-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_v3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('dealer', 'Dealer'), ('customer', 'Customer'), ('mechanic', 'Mechanic')], default='customer', max_length=20),
        ),
    ]
